-- V1: schema inicial migrado do Hibernate auto-generation
--
-- Este script cria todas as tabelas atualmente geradas pelas entidades JPA do projeto.
-- Nomenclatura: preserva os nomes default que o Hibernate (PhysicalNamingStrategyStandardImpl)
-- usa a partir do nome das classes/atributos. Para manter compatibilidade entre MariaDB e
-- PostgreSQL, os identificadores não são quotados (no PostgreSQL serão normalizados para
-- lowercase, o que também é o comportamento do Hibernate quando emite SQL sem aspas).
--
-- Estratégia de IDs: EntityClass usa GenerationType.IDENTITY. Para escrever DDL portável
-- entre MariaDB (10.3+) e PostgreSQL (10+) usamos o padrão SQL "GENERATED BY DEFAULT AS
-- IDENTITY", suportado nativamente nos dois bancos. Isso evita AUTO_INCREMENT (MariaDB-only)
-- e SERIAL (Postgres-only).

-- ============================================================================
-- Evento
-- ============================================================================
CREATE TABLE Evento (
    id            BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dataInclusao  TIMESTAMP    NULL,
    ativo         BOOLEAN      NULL,
    nome          VARCHAR(255) NULL,
    descricao     VARCHAR(255) NULL,
    local         VARCHAR(255) NULL,
    inicioEvento  TIMESTAMP    NULL,
    finalEvento   TIMESTAMP    NULL,
    CONSTRAINT pk_evento PRIMARY KEY (id)
);

-- ============================================================================
-- EspacoEvento
-- FK evento_espacoevento -> Evento.id (Evento @OneToMany com @JoinColumn)
-- ============================================================================
CREATE TABLE EspacoEvento (
    id                    BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dataInclusao          TIMESTAMP    NULL,
    ativo                 BOOLEAN      NULL,
    nome                  VARCHAR(255) NULL,
    evento_espacoevento   BIGINT       NULL,
    CONSTRAINT pk_espacoevento PRIMARY KEY (id),
    CONSTRAINT fk_espacoevento_evento FOREIGN KEY (evento_espacoevento) REFERENCES Evento (id)
);

-- ============================================================================
-- TipoIngresso
-- ============================================================================
CREATE TABLE TipoIngresso (
    id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dataInclusao TIMESTAMP    NULL,
    ativo        BOOLEAN      NULL,
    nome         VARCHAR(255) NULL,
    CONSTRAINT pk_tipoingresso PRIMARY KEY (id)
);

-- ============================================================================
-- TipoIngresso <-> EspacoEvento (join table do @ManyToMany)
-- Nome default do Hibernate para a join table: TipoIngresso_EspacoEvento
-- ============================================================================
CREATE TABLE TipoIngresso_EspacoEvento (
    TipoIngresso_id   BIGINT NOT NULL,
    espacoEventos_id  BIGINT NOT NULL,
    CONSTRAINT fk_tipoingresso_espacoevento_tipo
        FOREIGN KEY (TipoIngresso_id)  REFERENCES TipoIngresso (id),
    CONSTRAINT fk_tipoingresso_espacoevento_espaco
        FOREIGN KEY (espacoEventos_id) REFERENCES EspacoEvento (id)
);

-- ============================================================================
-- Ingresso
-- FK ingresso_tipoingresso -> TipoIngresso.id (@ManyToOne)
-- FK usuario_ingresso      -> Usuario.id      (Usuario @OneToMany com @JoinColumn)
-- ============================================================================
CREATE TABLE Ingresso (
    id                     BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dataInclusao           TIMESTAMP    NULL,
    ativo                  BOOLEAN      NULL,
    chaveAcesso            VARCHAR(255) NULL,
    lote                   VARCHAR(255) NULL,
    ingresso_tipoingresso  BIGINT       NULL,
    usuario_ingresso       BIGINT       NULL,
    CONSTRAINT pk_ingresso PRIMARY KEY (id),
    CONSTRAINT fk_ingresso_tipoingresso FOREIGN KEY (ingresso_tipoingresso) REFERENCES TipoIngresso (id)
);

-- ============================================================================
-- Usuario
-- ============================================================================
CREATE TABLE Usuario (
    id             BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dataInclusao   TIMESTAMP    NULL,
    ativo          BOOLEAN      NULL,
    nome           VARCHAR(70)  NOT NULL,
    email          VARCHAR(200) NOT NULL,
    senha          VARCHAR(255) NOT NULL,
    cpf            VARCHAR(255) NOT NULL,
    dataNascimento DATE         NULL,
    telefone       VARCHAR(255) NULL,
    naturalidade   VARCHAR(255) NULL,
    CONSTRAINT pk_usuario PRIMARY KEY (id)
);

-- FK usuario_ingresso depende de Usuario; adicionada aqui para evitar ordem circular.
ALTER TABLE Ingresso
    ADD CONSTRAINT fk_ingresso_usuario FOREIGN KEY (usuario_ingresso) REFERENCES Usuario (id);

-- ============================================================================
-- usuario_perfil (@ElementCollection de enum Perfil em Usuario)
-- @CollectionTable(name = "usuario_perfil"); @Column(name = "perfil", length = 30)
-- ============================================================================
CREATE TABLE usuario_perfil (
    id_usuario BIGINT      NOT NULL,
    perfil     VARCHAR(30) NULL,
    CONSTRAINT fk_usuario_perfil_usuario FOREIGN KEY (id_usuario) REFERENCES Usuario (id)
);
