-- V2: adiciona a tabela Empresa (tenant-root da atividade 001).
--
-- Mantém a mesma convenção do V1: identificadores sem aspas (camelCase preservado
-- pelo default do Hibernate). IDs como GENERATED BY DEFAULT AS IDENTITY para
-- portabilidade entre MariaDB 10.3+ e PostgreSQL 10+.

CREATE TABLE Empresa (
    id           BIGINT       NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    dataInclusao TIMESTAMP    NULL,
    ativo        BOOLEAN      NULL,
    nome         VARCHAR(255) NOT NULL,
    cnpj         VARCHAR(20)  NULL,
    status       VARCHAR(20)  NOT NULL,
    CONSTRAINT pk_empresa PRIMARY KEY (id),
    CONSTRAINT uk_empresa_cnpj UNIQUE (cnpj)
);
